-- Auto-generated by matugen
   local M = {}
   
   M.colors = {
       -- Primary colors
       primary = "#a3c9fe",
       on_primary = "#00315c",
       primary_container = "#1f4876",
       on_primary_container = "#d3e4ff",
       
       -- Secondary colors
       secondary = "#bcc7db",
       on_secondary = "#263141",
       
       -- Tertiary colors
       tertiary = "#d9bde3",
       on_tertiary = "#3c2947",
       
       -- Error colors
       error = "#ffb4ab",
       on_error = "#690005",
       
       -- Background colors
       background = "#111318",
       on_background = "#e1e2e8",
       surface = "#111318",
       on_surface = "#e1e2e8",
       
       -- Surface variants
       surface_variant = "#43474e",
       on_surface_variant = "#c3c6cf",
       
       -- Outline
       outline = "#8d9199",
       outline_variant = "#43474e",
   }
   
   return M
